version: "3.8"

services:
  # mysqldb:
  #   container_name: mysqldb
  #   image: mysql
  #   volumes: 
  #     - data:/var/lib/mysql
  #   ports:
  #     - '3306:3306'
  #   expose:
  #     - '3306'
  #   environment: 
  #     MYSQL_DATABASE: sorndb
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_PASSWORD: root
  #   networks: 
  #     - sorn-net

  backend:
    container_name: backend
    build: ./backend
    ports:
      - '4000:4000' 
    volumes:
      - /app/node_modules
      - ./backend:/app
    env_file: ./backend/.env 
    environment: 
      HOST: mysqldb
    # depends_on: 
    #   - mysqldb
    networks: 
      - sorn-net

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '3000:3000'
    env_file: ./frontend/.env.development.local
    stdin_open: true
    tty: true
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
    networks: 
      - sorn-net
      

volumes:
  data:
  
networks: 
  sorn-net:
    external: true